target 'rnxml' do

pod 'GDataXML-HTML', :git => 'https://github.com/graetzer/GDataXML-HTML', :branch => 'xpath-fix'
pod 'React', '~> 0.9.0'

end

target 'rnxmlTests' do

pod 'GDataXML-HTML', :git => 'https://github.com/graetzer/GDataXML-HTML', :branch => 'xpath-fix'

end
